//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Facilities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_Facilities()
        {
            this.LMIS_ExpectedReport = new HashSet<LMIS_ExpectedReport>();
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.fo_ClientFeedback = new HashSet<fo_ClientFeedback>();
            this.fo_complaint = new HashSet<fo_complaint>();
            this.fo_contact_person = new HashSet<fo_contact_person>();
            this.Order_DrugDetails_PhysicalCount = new HashSet<Order_DrugDetails_PhysicalCount>();
            this.Order_Header = new HashSet<Order_Header>();
            this.order_hiv_rapid_test_kit_header = new HashSet<order_hiv_rapid_test_kit_header>();
            this.order_hiv_rapid_test_kit_PhysicalCount = new HashSet<order_hiv_rapid_test_kit_PhysicalCount>();
            this.Order_Lab_Custom_Header = new HashSet<Order_Lab_Custom_Header>();
            this.Order_Lab_Header = new HashSet<Order_Lab_Header>();
            this.Order_Lab_PhysicalCount = new HashSet<Order_Lab_PhysicalCount>();
            this.Order_MAULT_Header = new HashSet<Order_MAULT_Header>();
            this.Order_OI_STI_Detail_Physical_Count = new HashSet<Order_OI_STI_Detail_Physical_Count>();
            this.Order_OI_STI_Header = new HashSet<Order_OI_STI_Header>();
            this.Order_RUTF_Header = new HashSet<Order_RUTF_Header>();
            this.Order_SMC_SLM_Header = new HashSet<Order_SMC_SLM_Header>();
            this.Order_SMC_SLM_Physical_Count = new HashSet<Order_SMC_SLM_Physical_Count>();
            this.Order_SMC_SLM_Summary = new HashSet<Order_SMC_SLM_Summary>();
            this.Order_TB_Header = new HashSet<Order_TB_Header>();
            this.Order_ViralLoadReagents_Header = new HashSet<Order_ViralLoadReagents_Header>();
            this.Order_ViralLoadReagents_Summary = new HashSet<Order_ViralLoadReagents_Summary>();
            this.A_Sector_Change = new HashSet<A_Sector_Change>();
            this.Treatment_Fluconazole = new HashSet<Treatment_Fluconazole>();
            this.fo_complaint1 = new HashSet<fo_complaint>();
        }
    
        public int FacilityCode { get; set; }
        public Nullable<int> DeliveryZoneCode { get; set; }
        public Nullable<int> ImplimentingPartnerCode { get; set; }
        public Nullable<int> DistrrictCode { get; set; }
        public string Facility { get; set; }
        public string SAP_Code { get; set; }
        public Nullable<bool> SupportedByMAUL { get; set; }
        public Nullable<bool> IsAccredited { get; set; }
        public Nullable<int> level_of_care { get; set; }
        public Nullable<int> client_type_code { get; set; }
        public Nullable<int> region_code { get; set; }
        public string RFSO_UserName { get; set; }
        public Nullable<int> OwnershipId { get; set; }
        public Nullable<int> CDCRegionId { get; set; }
        public string FacilityTypeId { get; set; }
        public string Longtitude { get; set; }
        public string Latititude { get; set; }
        public string Village_Id { get; set; }
        public Nullable<int> ComprehensiveImplimentingPartnerCode { get; set; }
        public Nullable<int> PatientLoadCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Nearest_Public_HF_Distance { get; set; }
        public string DSDM { get; set; }
        public bool Active_ART { get; set; }
    
        public virtual A_CDCRegion A_CDCRegion { get; set; }
        public virtual A_ClientType A_ClientType { get; set; }
        public virtual A_DeliveryZone A_DeliveryZone { get; set; }
        public virtual A_District A_District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LMIS_ExpectedReport> LMIS_ExpectedReport { get; set; }
        public virtual A_Facilities A_Facilities1 { get; set; }
        public virtual A_Facilities A_Facilities2 { get; set; }
        public virtual A_Facility_Level_Of_Care A_Facility_Level_Of_Care { get; set; }
        public virtual A_FacilityType A_FacilityType { get; set; }
        public virtual A_ImplimentingPartners A_ImplimentingPartners { get; set; }
        public virtual A_Ownership A_Ownership { get; set; }
        public virtual A_PatientLoad A_PatientLoad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fo_ClientFeedback> fo_ClientFeedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fo_complaint> fo_complaint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fo_contact_person> fo_contact_person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_DrugDetails_PhysicalCount> Order_DrugDetails_PhysicalCount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Header> Order_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_hiv_rapid_test_kit_header> order_hiv_rapid_test_kit_header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_hiv_rapid_test_kit_PhysicalCount> order_hiv_rapid_test_kit_PhysicalCount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Lab_Custom_Header> Order_Lab_Custom_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Lab_Header> Order_Lab_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Lab_PhysicalCount> Order_Lab_PhysicalCount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_MAULT_Header> Order_MAULT_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_OI_STI_Detail_Physical_Count> Order_OI_STI_Detail_Physical_Count { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_OI_STI_Header> Order_OI_STI_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_RUTF_Header> Order_RUTF_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_SMC_SLM_Header> Order_SMC_SLM_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_SMC_SLM_Physical_Count> Order_SMC_SLM_Physical_Count { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_SMC_SLM_Summary> Order_SMC_SLM_Summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_TB_Header> Order_TB_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_ViralLoadReagents_Header> Order_ViralLoadReagents_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_ViralLoadReagents_Summary> Order_ViralLoadReagents_Summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_Sector_Change> A_Sector_Change { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Treatment_Fluconazole> Treatment_Fluconazole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fo_complaint> fo_complaint1 { get; set; }
    }
}
