//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_Supplier()
        {
            this.fo_contact_person = new HashSet<fo_contact_person>();
        }
    
        public int supplier_code { get; set; }
        public string supplier_desc { get; set; }
        public Nullable<int> country_code { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> supplier_category { get; set; }
    
        public virtual A_Supplier_Status A_Supplier_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fo_contact_person> fo_contact_person { get; set; }
    }
}
