//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Venue_List
    {
        public int VenueID { get; set; }
        public int ID { get; set; }
        public string VenueListName { get; set; }
    
        public virtual A_Venue A_Venue { get; set; }
        public virtual A_Venue A_Venue1 { get; set; }
    }
}
