//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_Rutf
    {
        public int ItemNumber { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public string ItemDescription { get; set; }
        public string BasicUnit { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public Nullable<double> QuantityReceived { get; set; }
        public Nullable<double> Consumption { get; set; }
        public Nullable<double> LossesAdjustments { get; set; }
        public Nullable<double> ClosingBalance { get; set; }
        public Nullable<double> QuantityRequired { get; set; }
        public Nullable<int> FacilityCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<double> Quantity_Allocated { get; set; }
        public string Notes { get; set; }
        public string RFSONotes { get; set; }
    }
}
