//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_VehiclePackingListAllocation
    {
        public int FacilityCode { get; set; }
        public int DriverVehicleCode { get; set; }
        public string Facility { get; set; }
        public System.DateTime StartDate_OrderForm { get; set; }
        public System.DateTime EndDate_OrderForm { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<int> DeliveryZoneCode { get; set; }
    }
}
