//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_A_Product_Lab_Cat_2_3
    {
        public int product_category_code { get; set; }
        public Nullable<int> product_code { get; set; }
        public Nullable<int> category_2_code { get; set; }
        public Nullable<int> category_3_code { get; set; }
    }
}
