//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_HIV_Test_Kits_PC_Report
    {
        public int product_code { get; set; }
        public string product_description { get; set; }
        public string strength { get; set; }
        public string packsize { get; set; }
        public Nullable<int> carton_size_pkt { get; set; }
        public Nullable<double> carton_weight_kg { get; set; }
        public Nullable<int> product_category { get; set; }
        public Nullable<short> Basic_Unit { get; set; }
        public Nullable<int> ART_product_classification { get; set; }
        public string SAP_code { get; set; }
        public int FacilityCode { get; set; }
        public System.DateTime DateOfPhysicalCount { get; set; }
        public string BatchNo { get; set; }
        public Nullable<double> Quantity_Dispensary { get; set; }
        public Nullable<double> Quantity_Store { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<double> Total { get; set; }
        public string Comment { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<bool> record_status { get; set; }
        public Nullable<int> MonthsToExpire { get; set; }
    }
}
