//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_dist_kpi_maintenance
    {
        public string registration { get; set; }
        public Nullable<int> mMonth { get; set; }
        public Nullable<int> mYear { get; set; }
        public Nullable<int> Maintenance_Cost { get; set; }
        public Nullable<int> Days_In_Workshop { get; set; }
    }
}
