//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_OI_STI
    {
        public int ItemNumber { get; set; }
        public string ProductCode { get; set; }
        public string ItemDescription { get; set; }
        public string BasicUnit { get; set; }
        public Nullable<double> PhysicalCountAtBeginningOfReviewPeriod { get; set; }
        public Nullable<double> QuantityReceivedDuringTheTwoMonthsCycle { get; set; }
        public Nullable<double> QuantityUsedDuringTwoMonths { get; set; }
        public Nullable<double> LossesAndAdjustments { get; set; }
        public Nullable<double> NumberOfDaysOutOfStock { get; set; }
        public Nullable<double> ThisMonthPhysicalCount { get; set; }
        public Nullable<double> AMC { get; set; }
        public Nullable<double> MonthsOfStock { get; set; }
        public Nullable<double> MaximumStockQuantity { get; set; }
        public Nullable<double> QuantityRequired { get; set; }
        public string Notes { get; set; }
        public Nullable<double> Quantity_Allocated { get; set; }
        public string RFSONotes { get; set; }
        public int FacilityCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    }
}
