//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2
    {
        public string registration { get; set; }
        public Nullable<int> year_recorded { get; set; }
        public Nullable<int> month_recorded { get; set; }
        public Nullable<int> days_is_avialable { get; set; }
        public Nullable<int> days_in_use { get; set; }
        public Nullable<double> utilization { get; set; }
    }
}
