//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_dist_logbook
    {
        public Nullable<bool> check_box { get; set; }
        public string vehicle_registration { get; set; }
        public System.DateTime departure_date { get; set; }
        public string driver_permit { get; set; }
        public Nullable<int> source_facility { get; set; }
        public Nullable<int> source_other { get; set; }
        public Nullable<int> destination_facility { get; set; }
        public Nullable<int> destination_other { get; set; }
        public Nullable<int> ordometer_start { get; set; }
        public Nullable<int> ordometer_arrival { get; set; }
        public Nullable<int> distance_travelled { get; set; }
        public Nullable<int> fuel_added { get; set; }
        public Nullable<int> fuel_unit_cost { get; set; }
        public string passengers { get; set; }
        public Nullable<int> remarks { get; set; }
        public Nullable<int> make { get; set; }
        public Nullable<int> model { get; set; }
        public Nullable<int> fuel_type { get; set; }
        public Nullable<System.DateTime> time_arrival { get; set; }
        public System.DateTime time_start { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public string comment { get; set; }
    }
}
