//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_Laboratory_PhysicalCount
    {
        public int product_order { get; set; }
        public Nullable<int> product_code { get; set; }
        public string product_description { get; set; }
        public string Basic_Unit { get; set; }
        public string Form { get; set; }
        public Nullable<int> Quantity_Dispensary { get; set; }
        public Nullable<int> Quantity_Store { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> DateOfPhysicalCount { get; set; }
        public Nullable<int> FacilityCode { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ProductCategory { get; set; }
    }
}
