//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_fo_er_complaint_category
    {
        public Nullable<int> no_of_complaints { get; set; }
        public int e_reg_complaint_code { get; set; }
        public string complaint_category_desc { get; set; }
        public Nullable<System.DateTime> e_reg_date_recieved { get; set; }
    }
}
