//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_SMC_SLM_Emergency
    {
        public int FacilityCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime DatePrepared { get; set; }
        public int ProductCode { get; set; }
        public string Description { get; set; }
        public string UoM { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public Nullable<double> QtyRecieved { get; set; }
        public Nullable<double> Consumption { get; set; }
        public Nullable<double> LossesAndAdjustments { get; set; }
        public Nullable<double> TotalClosingBalance { get; set; }
        public Nullable<int> QuantityAllocated { get; set; }
        public Nullable<double> QuantityToOrder { get; set; }
        public string Comments { get; set; }
        public string RFSONotes { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public string Facility_UserName { get; set; }
        public Nullable<System.DateTime> Facility_UpdateDate { get; set; }
        public Nullable<bool> RFSO_SentBackTofacility { get; set; }
        public string RFSO_SentBackBy { get; set; }
        public Nullable<System.DateTime> RFSO_SentBackDate { get; set; }
        public string RFSO_ApprovedBy { get; set; }
        public Nullable<System.DateTime> RFSO_DateOfApproval { get; set; }
        public Nullable<bool> RFSO_ApproveOrder { get; set; }
        public Nullable<bool> EportedToSAP { get; set; }
        public string RFSONotes1 { get; set; }
        public Nullable<bool> FinalSubmission { get; set; }
        public int ItemNumber { get; set; }
    }
}
