//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_distribution_schedule
    {
        public string FacilityCode { get; set; }
        public System.DateTime Posting_Date { get; set; }
        public Nullable<int> posting_year { get; set; }
        public Nullable<int> posting_month { get; set; }
        public int DrugCode { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Lsat_Purchase_Price { get; set; }
        public string strength { get; set; }
        public string packsize { get; set; }
        public Nullable<int> carton_size_pkt { get; set; }
        public Nullable<double> carton_weight_kg { get; set; }
        public string weight { get; set; }
    }
}
