//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_hss_baseline_hf_services_staff_responsibility
    {
        public int hf_service_1_code { get; set; }
        public int hf_service_2_code { get; set; }
        public string hf_service_2_desc { get; set; }
        public string hf_service_1_desc { get; set; }
        public Nullable<int> facility_code { get; set; }
        public Nullable<System.DateTime> interview_date { get; set; }
        public string places_orders { get; set; }
        public string coordinate_delivery_transport { get; set; }
        public string recieves_supplies { get; set; }
        public string manages_stock { get; set; }
        public string supervises { get; set; }
    }
}
