//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_dist_kpi_incident
    {
        public Nullable<int> xMonth { get; set; }
        public Nullable<int> xYear { get; set; }
        public string vehicle_registartion { get; set; }
        public Nullable<int> No_Incidents { get; set; }
    }
}
