//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_hss_baseline_laboratory_machines
    {
        public Nullable<int> category_2_code { get; set; }
        public Nullable<int> category_3_code { get; set; }
        public int product_category_code { get; set; }
        public Nullable<int> product_code { get; set; }
        public string lab_cat_1_desc { get; set; }
        public string lab_cat_2_desc { get; set; }
        public string lab_cat_3_desc { get; set; }
        public string product_description { get; set; }
        public string avialability_service_contract { get; set; }
        public string service_provider { get; set; }
        public string service_frequency { get; set; }
        public string remarks { get; set; }
        public Nullable<int> facility_code { get; set; }
        public Nullable<System.DateTime> interview_date { get; set; }
    }
}
