//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Facility_GIS_Codinates
    {
        public int FacilityCode { get; set; }
        public string ZoneDescription { get; set; }
        public string ImplementingPartnerDescription { get; set; }
        public string District_Name { get; set; }
        public string CDCRegion { get; set; }
        public string level_of_care { get; set; }
        public string client_type_desc { get; set; }
        public string FacilityType { get; set; }
        public string OwnershipDescription { get; set; }
        public int Old_sector { get; set; }
        public Nullable<int> New_sector { get; set; }
        public string Facility { get; set; }
        public string SAP_Code { get; set; }
        public string Longtitude { get; set; }
        public string Latititude { get; set; }
    }
}
