//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_dist_kpi_logbook_a
    {
        public Nullable<int> xMonth { get; set; }
        public Nullable<int> xYear { get; set; }
        public string vehicle_registration { get; set; }
        public Nullable<int> Ordometer_Start_Month { get; set; }
        public Nullable<int> Ordometer_End_Month { get; set; }
        public Nullable<int> Fuel_Added { get; set; }
        public Nullable<int> Average_Fuel_Price { get; set; }
        public Nullable<int> Days_Worked { get; set; }
        public System.DateTime departure_date { get; set; }
        public Nullable<int> ordometer_arrival { get; set; }
        public System.DateTime time_start { get; set; }
        public Nullable<System.DateTime> time_arrival { get; set; }
    }
}
