//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_crystal_lmis_rr_arv_base
    {
        public Nullable<int> no_of_facilities { get; set; }
        public string Sector { get; set; }
        public Nullable<double> reporting_rate { get; set; }
        public Nullable<int> ReportingYear { get; set; }
        public Nullable<int> ReportingMonth { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime StartDate { get; set; }
    }
}
