//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_x_pmp_proc_matching_shipmet_plan_budget_a
    {
        public Nullable<System.DateTime> date_arrival_entry_port { get; set; }
        public string reference_no { get; set; }
    }
}
