//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_dist_kpi_vehicles_active_year_month
    {
        public Nullable<int> COP_Year { get; set; }
        public int quarter_id { get; set; }
        public Nullable<int> xYear { get; set; }
        public Nullable<int> xMonth { get; set; }
        public Nullable<int> vehicle_classification_id { get; set; }
        public Nullable<int> vehicles { get; set; }
    }
}
