//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_fo_complaint_current
    {
        public int e_reg_complaint_code { get; set; }
        public Nullable<System.DateTime> e_reg_date_recieved { get; set; }
        public Nullable<int> e_reg_complaint_category { get; set; }
        public string e_reg_complaint_details { get; set; }
        public Nullable<int> e_reg_affected_sites { get; set; }
        public Nullable<int> e_reg_product_category { get; set; }
        public Nullable<int> e_reg_communication_mode { get; set; }
        public Nullable<System.DateTime> e_reg_date_resolved { get; set; }
        public Nullable<System.DateTime> e_reg_expected_date_resolution { get; set; }
        public Nullable<int> e_reg_contact_person_id { get; set; }
        public Nullable<int> cp_title { get; set; }
        public Nullable<int> cp_facility { get; set; }
        public Nullable<int> cp_district { get; set; }
        public Nullable<int> cp_category { get; set; }
        public Nullable<int> cp_ip { get; set; }
        public Nullable<int> cp_supplier_code { get; set; }
        public Nullable<System.DateTime> e_reg_track_date_of_action { get; set; }
        public string e_reg_track_action_details { get; set; }
        public Nullable<int> e_reg_track_status { get; set; }
        public string e_reg_track_maul_staff { get; set; }
        public Nullable<int> e_reg_complaint_accuteness { get; set; }
        public int e_reg_track_code { get; set; }
        public Nullable<bool> DeletedRecord { get; set; }
        public Nullable<bool> is_quality_issue { get; set; }
    }
}
