//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_batch_del
    {
        public Nullable<bool> check_me { get; set; }
        public int FacilityCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public short RegimenCode { get; set; }
        public Nullable<int> Patients_Existing { get; set; }
        public Nullable<int> Patients_New { get; set; }
        public Nullable<int> Pregnant_Existing { get; set; }
        public Nullable<int> Pregnant_New { get; set; }
        public Nullable<int> J_MONTH { get; set; }
        public Nullable<int> J_YEAR { get; set; }
        public Nullable<int> Conflict { get; set; }
    }
}
