//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_crystal_lmis_expiry_tracking_lab_b
    {
        public int FacilityCode { get; set; }
        public Nullable<System.DateTime> DateOfPhysicalCount { get; set; }
        public string BatchNo { get; set; }
        public Nullable<double> Quantity_Dispensary { get; set; }
        public Nullable<double> Quantity_Store { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<double> Total { get; set; }
        public int product_code { get; set; }
        public Nullable<bool> record_status { get; set; }
    }
}
