//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_fo_Contacts_Details
    {
        public int cp_code { get; set; }
        public string cp_name { get; set; }
        public Nullable<int> cp_title { get; set; }
        public Nullable<int> cp_facility { get; set; }
        public Nullable<int> cp_district { get; set; }
        public Nullable<int> cp_category { get; set; }
        public Nullable<int> cp_ip { get; set; }
        public Nullable<int> cp_supplier_code { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<int> ct_telephon { get; set; }
        public Nullable<int> ct_telephone_2 { get; set; }
        public string ce_email { get; set; }
        public Nullable<bool> DisableReceived { get; set; }
        public Nullable<bool> DisableComfirmed { get; set; }
        public Nullable<bool> DisableProcessed { get; set; }
        public Nullable<bool> DisableDispatched { get; set; }
        public Nullable<bool> DisableDelivered { get; set; }
        public Nullable<bool> DisableAll { get; set; }
        public string User_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public string UserName { get; set; }
        public int AccessFailedCount { get; set; }
        public bool LockoutEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public string Id { get; set; }
        public string Role { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
