//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_export_atomic_All_Products
    {
        public string Facility { get; set; }
        public Nullable<int> DeliveryZoneCode { get; set; }
        public string ZoneDescription { get; set; }
        public Nullable<int> ImplimentingPartnerCode { get; set; }
        public string ImplementingPartnerDescription { get; set; }
        public Nullable<int> DistrrictCode { get; set; }
        public string District { get; set; }
        public string SAP_Code { get; set; }
        public int FacilityCode { get; set; }
        public Nullable<bool> SupportedByMAUL { get; set; }
        public Nullable<bool> IsAccredited { get; set; }
        public Nullable<int> level_of_care { get; set; }
        public string level_Desc { get; set; }
        public Nullable<int> client_type_code { get; set; }
        public string client_type_desc { get; set; }
        public Nullable<int> OwnershipId { get; set; }
        public string OwnershipDescription { get; set; }
        public Nullable<int> CDCRegionId { get; set; }
        public string CDCRegion { get; set; }
        public string FacilityTypeId { get; set; }
        public string FacilityType { get; set; }
        public Nullable<int> ComprehensiveImplimentingPartnerCode { get; set; }
        public string ComprehensiveImplementingPartnerDescription { get; set; }
        public Nullable<int> PatientLoadCode { get; set; }
        public string PatientLoadDescription { get; set; }
        public string SCTO { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> DatePrepared { get; set; }
        public Nullable<bool> EmergencyOrder { get; set; }
        public Nullable<bool> FinalSubmission { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public string Status { get; set; }
        public string OrderStatusIdChangedBy { get; set; }
        public Nullable<System.DateTime> OrderStatusIdDateChanged { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.DateTime> DateExpected { get; set; }
        public string Facility_UserName { get; set; }
        public Nullable<bool> RFSO_SentBackTofacility { get; set; }
        public string RFSO_SentBackBy { get; set; }
        public Nullable<System.DateTime> RFSO_SentBackDate { get; set; }
        public Nullable<bool> RFSO_ApproveOrder { get; set; }
        public string RFSO_ApprovedBy { get; set; }
        public Nullable<System.DateTime> RFSO_DateOfApproval { get; set; }
        public Nullable<int> product_code { get; set; }
        public string product_description { get; set; }
        public string strength { get; set; }
        public Nullable<short> Basic_Unit { get; set; }
        public string Product_SAP_Code { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public Nullable<double> QuantityRecieved { get; set; }
        public Nullable<double> PMTCT_Consumption { get; set; }
        public Nullable<double> ART_Consumption { get; set; }
        public Nullable<double> Losses_Adjustments { get; set; }
        public Nullable<double> ClosingBalance { get; set; }
        public Nullable<double> Months_Stock_atHand { get; set; }
        public Nullable<double> Quantity_Required_Current_Patients { get; set; }
        public Nullable<double> EstimatedNew_ART_Patients { get; set; }
        public Nullable<double> EstimatedNew_HIV_Pregnant { get; set; }
        public Nullable<double> DrugsRequired_NewPatients { get; set; }
        public Nullable<double> TotalDrugs_Required { get; set; }
        public string Notes { get; set; }
        public Nullable<double> Quantity_Allocated { get; set; }
        public string RFSONotes { get; set; }
        public Nullable<double> DaysOutOfStockDuring2Months { get; set; }
        public Nullable<double> AdjustedAMC { get; set; }
        public Nullable<double> ART_eMTCT_Consumption { get; set; }
        public string Product_Category { get; set; }
    }
}
