//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_TB
    {
        public string OrderNumber { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public Nullable<int> FacilityCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> Quantity_Allocated { get; set; }
        public string Comments { get; set; }
        public string RFSONotes { get; set; }
        public int ItemNumber { get; set; }
        public Nullable<int> SectionNumber { get; set; }
        public string Description { get; set; }
        public string PackSize { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public Nullable<double> QtyRecieved { get; set; }
        public Nullable<double> Dispensed2MonthsReview { get; set; }
        public Nullable<double> LossesAndAdjustments { get; set; }
        public Nullable<double> TotalClosingBalance { get; set; }
        public Nullable<double> DaysOutofStock { get; set; }
        public Nullable<double> AdjustedAMC { get; set; }
        public Nullable<double> ClosingBalance { get; set; }
        public Nullable<double> MonthsOfStock { get; set; }
    }
}
