//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_crystal_lmis_rr_lab_x3
    {
        public Nullable<int> NoReported { get; set; }
        public string Sector { get; set; }
        public Nullable<int> bYear { get; set; }
        public Nullable<int> bMonth { get; set; }
        public string Month_desc { get; set; }
        public Nullable<int> ExpectedReports { get; set; }
        public int NoReportedOnTime { get; set; }
        public Nullable<int> NoNotReported { get; set; }
    }
}
