//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_xa_amc
    {
        public int FacilityCode { get; set; }
        public System.DateTime DateOfAMC { get; set; }
        public int product_code { get; set; }
        public Nullable<double> AMC { get; set; }
        public string Comment { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<bool> record_status { get; set; }
    }
}
