//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_export_atomic_arv_emergency
    {
        public Nullable<int> DeliveryZoneCode { get; set; }
        public Nullable<int> ImplimentingPartnerCode { get; set; }
        public Nullable<int> DistrrictCode { get; set; }
        public string SAP_Code { get; set; }
        public Nullable<int> FacilityCode { get; set; }
        public Nullable<bool> SupportedByMAUL { get; set; }
        public Nullable<bool> IsAccredited { get; set; }
        public Nullable<int> level_of_care { get; set; }
        public Nullable<int> product_code { get; set; }
        public string product_description { get; set; }
        public string strength { get; set; }
        public string packsize { get; set; }
        public Nullable<int> carton_size_pkt { get; set; }
        public Nullable<double> carton_weight_kg { get; set; }
        public Nullable<short> Basic_Unit { get; set; }
        public Nullable<bool> approved_MOH_NTG { get; set; }
        public Nullable<bool> approved_WHO { get; set; }
        public Nullable<bool> approved_FDA { get; set; }
        public Nullable<int> nda_registration { get; set; }
        public string Product_SAP_Code { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime DatePrepared { get; set; }
        public Nullable<bool> RecordStatus { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<bool> FinalSubmission { get; set; }
        public string Facility_UserName { get; set; }
        public Nullable<bool> RFSO_SentBackTofacility { get; set; }
        public string RFSO_SentBackBy { get; set; }
        public Nullable<System.DateTime> RFSO_SentBackDate { get; set; }
        public Nullable<bool> RFSO_ApproveOrder { get; set; }
        public string RFSO_ApprovedBy { get; set; }
        public Nullable<System.DateTime> RFSO_DateOfApproval { get; set; }
        public Nullable<bool> EportedToSAP { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public Nullable<double> QuantityRecieved { get; set; }
        public Nullable<double> PMTCT_Consumption { get; set; }
        public Nullable<double> ART_Consumption { get; set; }
        public Nullable<double> Losses_Adjustments { get; set; }
        public Nullable<double> ClosingBalance { get; set; }
        public Nullable<double> Months_Stock_atHand { get; set; }
        public Nullable<double> Quantity_Required_Current_Patients { get; set; }
        public Nullable<double> EstimatedNew_ART_Patients { get; set; }
        public Nullable<double> EstimatedNew_HIV_Pregnant { get; set; }
        public Nullable<double> DrugsRequired_NewPatients { get; set; }
        public Nullable<double> TotalDrugs_Required { get; set; }
        public Nullable<double> Quantity_Allocated { get; set; }
        public string Notes { get; set; }
        public string RFSONotes { get; set; }
        public Nullable<double> DaysOutOfStockDuring2Months { get; set; }
        public Nullable<double> AdjustedAMC { get; set; }
        public Nullable<double> ART_eMTCT_Consumption { get; set; }
    }
}
