//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_x_pmp_proc_correctly_filled_POS_a
    {
        public string reference_no { get; set; }
        public Nullable<double> quantity_recieved_maul { get; set; }
        public Nullable<int> order_category { get; set; }
    }
}
