//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_hss_baseline_laboratory_checklist
    {
        public int lab_checklist_1_code { get; set; }
        public string lab_checklist_1_desc { get; set; }
        public Nullable<int> facility_code { get; set; }
        public Nullable<System.DateTime> interview_date { get; set; }
        public string yes_no { get; set; }
    }
}
