//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_fo_complaint_history
    {
        public int e_reg_track_complaint_code { get; set; }
        public int e_reg_track_code { get; set; }
        public Nullable<System.DateTime> e_reg_track_date_of_action { get; set; }
        public Nullable<int> e_reg_track_action_category { get; set; }
        public string e_reg_track_action_details { get; set; }
        public string e_reg_track_maul_staff { get; set; }
        public Nullable<int> e_reg_track_status { get; set; }
        public string e_reg_track_added_by { get; set; }
        public Nullable<System.DateTime> e_reg_track_added_date { get; set; }
    }
}
