//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_dist_kpi_fuel_consumption
    {
        public string vehicle_registration { get; set; }
        public Nullable<int> byear { get; set; }
        public Nullable<int> bmonth { get; set; }
        public Nullable<int> KilometresTravelled { get; set; }
        public Nullable<int> FuelAdded { get; set; }
        public Nullable<double> FuelConsumption { get; set; }
    }
}
