//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_export_atomic_lab_emergency
    {
        public Nullable<int> DeliveryZoneCode { get; set; }
        public Nullable<int> ImplimentingPartnerCode { get; set; }
        public Nullable<int> DistrrictCode { get; set; }
        public string SAP_Code { get; set; }
        public int FacilityCode { get; set; }
        public Nullable<bool> SupportedByMAUL { get; set; }
        public Nullable<bool> IsAccredited { get; set; }
        public Nullable<int> level_of_care { get; set; }
        public int product_code { get; set; }
        public string product_description { get; set; }
        public string strength { get; set; }
        public string packsize { get; set; }
        public Nullable<int> carton_size_pkt { get; set; }
        public Nullable<double> carton_weight_kg { get; set; }
        public Nullable<int> product_category { get; set; }
        public Nullable<short> Basic_Unit { get; set; }
        public Nullable<bool> approved_MOH_NTG { get; set; }
        public Nullable<bool> approved_WHO { get; set; }
        public Nullable<bool> approved_FDA { get; set; }
        public Nullable<int> nda_registration { get; set; }
        public string Product_SAP_Code { get; set; }
        public string lab_cat_1_desc { get; set; }
        public string lab_cat_2_desc { get; set; }
        public string lab_cat_3_desc { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public System.DateTime date_completed { get; set; }
        public Nullable<double> opening_balance { get; set; }
        public Nullable<double> quantity_recieved { get; set; }
        public Nullable<double> consumption { get; set; }
        public Nullable<double> losses_adjustment { get; set; }
        public Nullable<double> closing_balance { get; set; }
        public Nullable<double> quantity_to_order { get; set; }
        public Nullable<int> quantity_allocated { get; set; }
        public Nullable<double> total_cost { get; set; }
        public string comments { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<bool> RecordStatus { get; set; }
        public Nullable<bool> FinalSubmission { get; set; }
        public string Facility_UserName { get; set; }
        public Nullable<bool> RFSO_SentBackTofacility { get; set; }
        public string RFSO_SentBackBy { get; set; }
        public Nullable<System.DateTime> RFSO_SentBackDate { get; set; }
        public string RFSO_ApprovedBy { get; set; }
        public Nullable<System.DateTime> RFSO_DateOfApproval { get; set; }
        public Nullable<bool> RFSO_ApproveOrder { get; set; }
        public Nullable<bool> EportedToSAP { get; set; }
        public string RFSONotes { get; set; }
        public Nullable<bool> OnlyConsummableProducts { get; set; }
    }
}
