//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_Laboratory
    {
        public int product_order { get; set; }
        public Nullable<int> product_code { get; set; }
        public string product_description { get; set; }
        public string Basic_Unit { get; set; }
        public Nullable<int> FacilityCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> opening_balance { get; set; }
        public Nullable<double> quantity_recieved { get; set; }
        public Nullable<double> consumption { get; set; }
        public Nullable<double> losses_adjustment { get; set; }
        public Nullable<double> closing_balance { get; set; }
        public Nullable<double> quantity_to_order { get; set; }
        public Nullable<double> quantity_allocated { get; set; }
        public Nullable<double> total_cost { get; set; }
        public string comments { get; set; }
        public string RFSONotes { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<int> original_product_code { get; set; }
        public string Classification { get; set; }
        public Nullable<int> product_category { get; set; }
    }
}
