//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_A_ExpectedReports
    {
        public Nullable<int> DeliveryZoneCode { get; set; }
        public Nullable<int> ImplimentingPartnerCode { get; set; }
        public Nullable<int> DistrrictCode { get; set; }
        public Nullable<int> level_of_care { get; set; }
        public int FacilityCode { get; set; }
        public string Facility { get; set; }
        public Nullable<bool> ARV { get; set; }
        public Nullable<bool> TESTKITS { get; set; }
        public Nullable<bool> SMC { get; set; }
        public Nullable<bool> LABORATORY { get; set; }
    }
}
