//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_dist_operator_permit
    {
        public string driver_permit_number { get; set; }
        public string Name { get; set; }
        public Nullable<bool> valid_permit { get; set; }
        public string operator_id { get; set; }
        public Nullable<int> permit_category { get; set; }
        public Nullable<System.DateTime> permit_date_of_issue { get; set; }
        public Nullable<System.DateTime> permit_expiry_date { get; set; }
        public Nullable<int> job_title { get; set; }
    }
}
