//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_dist_kpi_graph_b
    {
        public Nullable<int> COP_Year { get; set; }
        public int quarter_id { get; set; }
        public Nullable<int> xMonth { get; set; }
        public Nullable<int> xYear { get; set; }
        public Nullable<System.DateTime> departure_date { get; set; }
        public string vehicle_registration { get; set; }
        public Nullable<int> ordometer_start { get; set; }
        public Nullable<int> ordometer_end { get; set; }
        public Nullable<int> Fuel_Added { get; set; }
        public Nullable<int> Average_Fuel_Price { get; set; }
        public Nullable<int> Days_Worked { get; set; }
        public Nullable<int> Maintenance_Cost { get; set; }
        public Nullable<int> Days_In_Workshop { get; set; }
        public Nullable<int> Working_Days_Month { get; set; }
        public Nullable<int> No_Incidents { get; set; }
        public Nullable<int> kpi_KilometersTravelled { get; set; }
        public Nullable<double> kpi_FuelConsumption { get; set; }
        public Nullable<double> kpi_RunningCostPerKm { get; set; }
        public Nullable<double> kpi_Avialability { get; set; }
        public Nullable<double> kpi_Utilization { get; set; }
        public Nullable<int> vehicle_classification_id { get; set; }
        public string vehicle_classification { get; set; }
    }
}
