//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_x_pmp_dist_delivery_cycle_time_a
    {
        public Nullable<int> xMonth { get; set; }
        public Nullable<int> xYear { get; set; }
        public Nullable<System.DateTime> time_arrival { get; set; }
        public System.DateTime time_start { get; set; }
        public Nullable<int> remarks { get; set; }
        public Nullable<int> TimeInHours { get; set; }
    }
}
