//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_fo_complaint_AffectedSites
    {
        public int e_reg_complaint_code { get; set; }
        public string e_reg_complaint_No { get; set; }
        public Nullable<int> e_reg_contact_person_id { get; set; }
        public Nullable<System.DateTime> e_reg_date_recieved { get; set; }
        public Nullable<System.DateTime> e_reg_date_complaint { get; set; }
        public Nullable<int> e_reg_complaint_category { get; set; }
        public string e_reg_complaint_Title { get; set; }
        public string e_reg_complaint_details { get; set; }
        public Nullable<int> e_reg_MAUL_Staff { get; set; }
        public Nullable<int> e_reg_complaint_status { get; set; }
        public Nullable<int> e_reg_affected_sites { get; set; }
        public Nullable<int> e_reg_product_category { get; set; }
        public Nullable<int> e_reg_communication_mode { get; set; }
        public Nullable<System.DateTime> e_reg_date_resolved { get; set; }
        public Nullable<System.DateTime> e_reg_expected_date_resolution { get; set; }
        public Nullable<int> e_reg_complaint_accuteness { get; set; }
        public Nullable<bool> DeletedRecord { get; set; }
        public Nullable<bool> is_quality_issue { get; set; }
        public string AffectedSites { get; set; }
        public string FacilityCode { get; set; }
        public Nullable<bool> Sup_Doc_Evidence_Rec { get; set; }
        public Nullable<bool> Prod_Samples_Provided { get; set; }
        public string Communicated_By_Lev1 { get; set; }
        public string Communicated_By_Lev1Title { get; set; }
        public Nullable<System.DateTime> Communicated_By_Lev1Date { get; set; }
        public Nullable<bool> Email_letter_attached { get; set; }
        public Nullable<int> Communicated_By_Lev2 { get; set; }
        public string Communicated_By_Lev2Title { get; set; }
        public Nullable<System.DateTime> Communicated_By_Lev2Date { get; set; }
        public Nullable<bool> Communicated_By_Lev2Email { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> Feedback_Communicated { get; set; }
        public Nullable<System.DateTime> Feedback_Date { get; set; }
        public string Brief_Feedback_Desc { get; set; }
        public string No_Feedback_Reason { get; set; }
        public string ComplainantName { get; set; }
        public string ComplainantTitle { get; set; }
        public string ComplainantEmail { get; set; }
        public string ComplainantMobile { get; set; }
        public string ComplainantPhone { get; set; }
        public Nullable<int> ComplainantFacilityCode { get; set; }
        public Nullable<int> ComplainantDistrict { get; set; }
        public Nullable<int> IP { get; set; }
        public Nullable<int> FinalSubmission { get; set; }
        public Nullable<int> ComplainantCategory { get; set; }
    }
}
