//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_x_pmp_proc_correctly_filled_POS
    {
        public Nullable<double> award_quantity_ordered { get; set; }
        public Nullable<double> quantity_recieved_maul { get; set; }
        public Nullable<int> order_year { get; set; }
        public Nullable<int> order_quater { get; set; }
        public string reference_no { get; set; }
        public Nullable<System.DateTime> award_new_due_date { get; set; }
        public Nullable<System.DateTime> award_expected_date_delivery { get; set; }
    }
}
