//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_hss_baseline_focus_group_discussion
    {
        public string method_desc { get; set; }
        public string sub_indicator_desc { get; set; }
        public string indicator_desc { get; set; }
        public int indicator_code { get; set; }
        public int sub_indicator_code { get; set; }
        public Nullable<int> facility_code { get; set; }
        public Nullable<System.DateTime> interview_date { get; set; }
        public string yes_no { get; set; }
        public string remarks { get; set; }
    }
}
