//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_ARV_AMC
    {
        public int product_order { get; set; }
        public Nullable<int> product_code { get; set; }
        public string product_numbering { get; set; }
        public string product_description { get; set; }
        public string Basic_Unit { get; set; }
        public Nullable<double> AMC { get; set; }
        public string comment { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> record_status { get; set; }
        public Nullable<bool> amc_equal_to_zero { get; set; }
        public Nullable<int> FacilityCode { get; set; }
        public Nullable<System.DateTime> date_AMC { get; set; }
    }
}
