//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_fo_QI_CloseOut_Certificate
    {
        public int Id { get; set; }
        public int e_reg_complaint_code { get; set; }
        public int product_code { get; set; }
        public string batch_no { get; set; }
        public string e_reg_complaint_No { get; set; }
        public string Summary_of_Investigations { get; set; }
        public Nullable<int> Release_Instruction { get; set; }
        public string Other_attachment { get; set; }
        public Nullable<int> Warehouse_Officer { get; set; }
        public Nullable<System.DateTime> Warehouse_Date { get; set; }
        public Nullable<int> Finance_Manager { get; set; }
        public Nullable<System.DateTime> Finance_Date { get; set; }
        public Nullable<int> Director_Technical { get; set; }
        public Nullable<System.DateTime> Director_Technical_Date { get; set; }
        public Nullable<int> Executive_Director { get; set; }
        public Nullable<System.DateTime> Executive_Director_Date { get; set; }
        public Nullable<int> Complaint_Report { get; set; }
        public string Complaint_Report_Comment { get; set; }
        public Nullable<int> Notification_PAC { get; set; }
        public string Notification_PAC_Comment { get; set; }
        public Nullable<int> Notification_Vendor { get; set; }
        public string Notification_Vendor_Comment { get; set; }
        public Nullable<int> Product_COAs { get; set; }
        public string Product_COAs_Comment { get; set; }
        public Nullable<int> CAPA { get; set; }
        public string CAPA_Comment { get; set; }
        public Nullable<int> Returned_Note { get; set; }
        public string Returned_Note_Comment { get; set; }
        public Nullable<int> Credit_Note { get; set; }
        public string Credit_Note_Comment { get; set; }
        public Nullable<int> Reconciliation { get; set; }
        public string Reconciliation_Comment { get; set; }
        public Nullable<int> NDA_Notification { get; set; }
        public string NDA_Notification_Comment { get; set; }
    }
}
