//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_ARV_Patients
    {
        public int product_order { get; set; }
        public Nullable<short> regimen_code { get; set; }
        public string Regimen { get; set; }
        public int No_Existing { get; set; }
        public int No_New { get; set; }
        public int Pregnant_Existing { get; set; }
        public int Pregnant_New { get; set; }
        public Nullable<int> FacilityCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
