//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_crystal_lmis_summary_ip
    {
        public Nullable<int> NoOfFacilities { get; set; }
        public Nullable<int> mYear { get; set; }
        public Nullable<int> mMonth { get; set; }
        public string Month_desc { get; set; }
        public int ImplimentingPartnerCode { get; set; }
        public string ImplementingPartnerDescription { get; set; }
    }
}
