//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_RecipientEmail
    {
        public Nullable<int> ct_telephone { get; set; }
        public string ce_email { get; set; }
        public string cp_name { get; set; }
        public string title_desc { get; set; }
        public int FacilityCode { get; set; }
        public Nullable<int> DeliveryZoneCode { get; set; }
        public string Facility { get; set; }
        public int cp_code { get; set; }
        public Nullable<bool> DisableReceived { get; set; }
        public Nullable<bool> DisableProcessed { get; set; }
        public Nullable<bool> DisableDispatched { get; set; }
        public Nullable<bool> DisableDelivered { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> DisableComfirmed { get; set; }
        public Nullable<bool> DisableAll { get; set; }
    }
}
