//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_xa_regimen
    {
        public short RegimenCode { get; set; }
        public string RegimenDesc { get; set; }
        public string ExtraInfo { get; set; }
        public string DrugCombination { get; set; }
        public Nullable<short> RegimenCategoryCode { get; set; }
        public Nullable<bool> StandardRegimen { get; set; }
        public string RegimenCategoryDesc { get; set; }
        public int regimen_classification_code { get; set; }
        public string regimen_classification_desc { get; set; }
    }
}
