//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_crystal_lmis_expiry_tracking_testkits
    {
        public Nullable<int> ImplimentingPartnerCode { get; set; }
        public string ImplementingPartnerDescription { get; set; }
        public Nullable<int> level_of_care_code { get; set; }
        public string level_of_care { get; set; }
        public Nullable<int> DeliveryZoneCode { get; set; }
        public string Facility { get; set; }
        public string SAP_code { get; set; }
        public string product_description { get; set; }
        public string packsize { get; set; }
        public Nullable<System.DateTime> DateOfPhysicalCount { get; set; }
        public string BatchNo { get; set; }
        public Nullable<double> Quantity_Dispensary { get; set; }
        public Nullable<double> Quantity_Store { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<double> Quantity { get; set; }
    }
}
