//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_x_pmp_dist_delivery_cycle_time_b
    {
        public int quarter_id { get; set; }
        public Nullable<int> COP_Year { get; set; }
        public Nullable<int> TimeInHours { get; set; }
    }
}
