//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_fo_complaint_current_quality_issue
    {
        public int e_reg_complaint_code { get; set; }
        public Nullable<System.DateTime> e_reg_date_recieved { get; set; }
        public Nullable<int> e_reg_complaint_category { get; set; }
        public string e_reg_complaint_details { get; set; }
        public Nullable<int> e_reg_affected_sites { get; set; }
        public Nullable<int> e_reg_product_category { get; set; }
        public Nullable<int> e_reg_communication_mode { get; set; }
        public Nullable<System.DateTime> e_reg_date_resolved { get; set; }
        public Nullable<System.DateTime> e_reg_expected_date_resolution { get; set; }
        public Nullable<int> e_reg_contact_person_id { get; set; }
        public Nullable<int> cp_title { get; set; }
        public Nullable<int> cp_facility { get; set; }
        public Nullable<int> cp_district { get; set; }
        public Nullable<int> cp_category { get; set; }
        public Nullable<int> cp_ip { get; set; }
        public Nullable<int> cp_supplier_code { get; set; }
        public Nullable<System.DateTime> e_reg_track_date_of_action { get; set; }
        public string e_reg_track_action_details { get; set; }
        public Nullable<int> e_reg_track_status { get; set; }
        public string e_reg_track_maul_staff { get; set; }
        public Nullable<int> e_reg_complaint_accuteness { get; set; }
        public int e_reg_track_code { get; set; }
        public Nullable<bool> DeletedRecord { get; set; }
        public Nullable<bool> is_quality_issue { get; set; }
        public string batch_no { get; set; }
        public string complainant_name { get; set; }
        public Nullable<int> complainant_phone { get; set; }
        public Nullable<int> complainant_title { get; set; }
        public string complainant_email { get; set; }
        public Nullable<int> product_code { get; set; }
        public string product_strength { get; set; }
        public string dosage_form { get; set; }
        public string product_other { get; set; }
        public string manufacturer { get; set; }
        public Nullable<System.DateTime> date_quality_issue_identified { get; set; }
        public string description_of_quality_issue { get; set; }
        public Nullable<int> intervention_taken { get; set; }
        public string intervention_taken_other { get; set; }
        public string recipient_name { get; set; }
        public Nullable<int> recipient_title { get; set; }
        public Nullable<bool> attached_picture { get; set; }
        public Nullable<bool> attached_email { get; set; }
        public Nullable<bool> attached_note_letter { get; set; }
        public byte[] attached_image_picture { get; set; }
        public string attached_image_email { get; set; }
        public string attached_image_letter { get; set; }
    }
}
