//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_HIV_Test_Kits_Summary
    {
        public int product_order { get; set; }
        public Nullable<int> product_code { get; set; }
        public string product_description { get; set; }
        public Nullable<int> FacilityCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int HCT { get; set; }
        public int PMTCT { get; set; }
        public int Clinical_Diagnosis { get; set; }
        public int SMC { get; set; }
        public int Quality_Control { get; set; }
        public int Total { get; set; }
    }
}
