//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_HIV_Test_Kits
    {
        public int product_order { get; set; }
        public Nullable<int> product_code { get; set; }
        public string Basic_Unit { get; set; }
        public Nullable<int> FacilityCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> No_Test_Start_2Months { get; set; }
        public Nullable<double> Test_Recieved_2Months { get; set; }
        public Nullable<double> Test_Used_2Months { get; set; }
        public Nullable<double> Loss_Adjustment { get; set; }
        public Nullable<double> Test_Remaining { get; set; }
        public Nullable<double> Maximum_Stock { get; set; }
        public Nullable<double> Qunatity_On_Order { get; set; }
        public Nullable<double> Quantity_Required { get; set; }
        public string Quantity_To_Ship { get; set; }
        public string RFSONotes { get; set; }
        public Nullable<double> Quantity_Allocated { get; set; }
        public string product_description { get; set; }
    }
}
