//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_SMC_SLM_PhysicalCount
    {
        public int ItemNumber { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public string Description { get; set; }
        public string UnitPack { get; set; }
        public string Form { get; set; }
        public Nullable<int> Quantity_Dispensary { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> DateOfPhysicalCount { get; set; }
        public Nullable<int> FacilityCode { get; set; }
        public string Comment { get; set; }
    }
}
