//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_crystal_lmis_summary_expected
    {
        public int facility_code { get; set; }
        public Nullable<int> mYear { get; set; }
        public Nullable<int> mMonth { get; set; }
        public string Facility { get; set; }
        public string PC { get; set; }
    }
}
