//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_HIV_Test_Kits_ReportHeader
    {
        public string Facility { get; set; }
        public string District_Name { get; set; }
        public Nullable<int> DeliveryZoneCode { get; set; }
        public int FacilityCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> DatePrepared { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<bool> FinalSubmission { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public Nullable<System.DateTime> DateExpected { get; set; }
        public string Status { get; set; }
        public string OrderType { get; set; }
    }
}
