//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_ARV_ReportExtraRegimen
    {
        public string regimen_classification_desc { get; set; }
        public string RegimenCategoryDesc { get; set; }
        public int regimen_classification_code { get; set; }
        public short RegimenCategoryCode { get; set; }
        public string RegimenDesc { get; set; }
        public Nullable<int> Patients_Existing { get; set; }
        public Nullable<int> Patients_New { get; set; }
        public int FacilityCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string OrderNumber { get; set; }
        public short RegimenCode { get; set; }
    }
}
