//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_hss_baseline_laboratory
    {
        public int lab_assessment_qn_code { get; set; }
        public int lab_indicator_code { get; set; }
        public string lab_assessment_qn_desc { get; set; }
        public string laboratory_method_desc { get; set; }
        public string laboratory_indicator_desc { get; set; }
        public Nullable<int> facility_code { get; set; }
        public Nullable<System.DateTime> interview_date { get; set; }
        public string laboratory_yes_no { get; set; }
        public string laboratory_remarks { get; set; }
    }
}
