//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_dist_schedule
    {
        public Nullable<bool> Select_ { get; set; }
        public string District_Name { get; set; }
        public string DeliveryZoneCode { get; set; }
        public int FacilityCode { get; set; }
        public string Facility { get; set; }
        public string level_of_care { get; set; }
        public Nullable<System.DateTime> departure_date { get; set; }
        public Nullable<System.DateTime> expected_date_at_site { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<System.DateTime> actual_date_at_site { get; set; }
        public Nullable<int> status_delivey_id { get; set; }
        public string maul_staff { get; set; }
        public string vehicle_registration { get; set; }
        public string driver_permit_number { get; set; }
        public string Remark { get; set; }
        public Nullable<double> total_weight_cartons { get; set; }
        public Nullable<double> total_no_cartons { get; set; }
    }
}
