//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_hss_baseline_tools_review
    {
        public int tools_review_1_code { get; set; }
        public int tools_review_2_code { get; set; }
        public string tools_review_1_desc { get; set; }
        public string tools_review_2_desc { get; set; }
        public Nullable<int> facility_code { get; set; }
        public Nullable<System.DateTime> interview_date { get; set; }
        public string avialable { get; set; }
        public string displayed { get; set; }
    }
}
