//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_A_Facility
    {
        public int FacilityCode { get; set; }
        public Nullable<int> DeliveryZoneCode { get; set; }
        public Nullable<int> ImplimentingPartnerCode { get; set; }
        public Nullable<int> DistrrictCode { get; set; }
        public string Facility { get; set; }
        public string SAP_Code { get; set; }
        public Nullable<bool> SupportedByMAUL { get; set; }
        public Nullable<bool> IsAccredited { get; set; }
        public Nullable<int> level_of_care { get; set; }
        public Nullable<int> client_type_code { get; set; }
        public Nullable<int> region_code { get; set; }
        public string RFSO_UserName { get; set; }
        public Nullable<int> OwnershipId { get; set; }
        public Nullable<int> CDCRegionId { get; set; }
        public string FacilityTypeId { get; set; }
        public string Longtitude { get; set; }
        public string Latititude { get; set; }
        public string Village_Id { get; set; }
        public Nullable<int> ComprehensiveImplimentingPartnerCode { get; set; }
        public Nullable<int> PatientLoadCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Nearest_Public_HF_Distance { get; set; }
        public string DSDM { get; set; }
        public string SCTO { get; set; }
        public bool Active_ART { get; set; }
    }
}
