//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_crystal_lmis_patient_no_base
    {
        public Nullable<int> DeliveryZoneCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> summary_year { get; set; }
        public Nullable<int> summary_month { get; set; }
        public short RegimenCode { get; set; }
        public Nullable<int> Patients_Existing { get; set; }
        public Nullable<int> Patients_New { get; set; }
        public Nullable<int> Total_Patients { get; set; }
        public string Facility { get; set; }
        public string RegimenCategoryDesc { get; set; }
        public string regimen_classification_desc { get; set; }
        public string District_Name { get; set; }
        public string RegimenDesc { get; set; }
    }
}
