//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_hss_baseline_hf_services
    {
        public int hf_service_1_code { get; set; }
        public int hf_service_2_code { get; set; }
        public string hf_service_2_desc { get; set; }
        public string hf_service_1_desc { get; set; }
        public Nullable<int> facility_code { get; set; }
        public Nullable<System.DateTime> interview_date { get; set; }
        public string hf_service_value { get; set; }
        public Nullable<System.DateTime> hf_service_date_time { get; set; }
        public string hf_service_remarks { get; set; }
    }
}
