//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_hss_baseline_pharmacy
    {
        public int assessment_qn_code { get; set; }
        public int pharmacy_indicator_code { get; set; }
        public string assessment_qn_desc { get; set; }
        public string pharmacy_method_desc { get; set; }
        public string pharmacy_indicator_desc { get; set; }
        public Nullable<int> facility_code { get; set; }
        public Nullable<System.DateTime> interview_date { get; set; }
        public string yes_no { get; set; }
        public string remarks { get; set; }
    }
}
