//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_ViralLoadReagents
    {
        public int item_id { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public string ProductDescription { get; set; }
        public string PackSize { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public Nullable<double> QuantityRecieved { get; set; }
        public Nullable<double> Consumption { get; set; }
        public Nullable<double> LossesAndAdjustments { get; set; }
        public Nullable<double> TotalClosingBalance { get; set; }
        public Nullable<double> QuantityOrdered { get; set; }
        public string Comment { get; set; }
        public Nullable<double> Quantity_Allocated { get; set; }
        public string RFSONotes { get; set; }
        public Nullable<int> FacilityCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
