//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_WebTemplate_SMC_SLM
    {
        public int ItemNumber { get; set; }
        public Nullable<int> SectionNumber { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public string Description { get; set; }
        public string UoM { get; set; }
        public int FacilityCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public Nullable<double> QtyRecieved { get; set; }
        public Nullable<double> Consumption { get; set; }
        public Nullable<double> LossesAndAdjustments { get; set; }
        public Nullable<double> TotalClosingBalance { get; set; }
        public Nullable<double> QuantityToOrder { get; set; }
        public Nullable<int> QuantityAllocated { get; set; }
        public string Comments { get; set; }
        public string RFSONotes { get; set; }
    }
}
