//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_fo_Certificate_Release_frm_Quarantine
    {
        public int Id { get; set; }
        public int e_reg_complaint_code { get; set; }
        public string batch_no { get; set; }
        public int product_code { get; set; }
        public int cp_code { get; set; }
        public string Staff_name { get; set; }
        public Nullable<int> Staff_phone { get; set; }
        public Nullable<int> Staff_Designation { get; set; }
        public string Staff_email { get; set; }
        public Nullable<System.DateTime> Date_request { get; set; }
        public string product_strength { get; set; }
        public string dosage_form { get; set; }
        public string product_other { get; set; }
        public string manufacturer { get; set; }
        public Nullable<System.DateTime> Manufacture_date { get; set; }
        public Nullable<System.DateTime> Expiry_date { get; set; }
        public string Supplier { get; set; }
        public string e_reg_complaint_No { get; set; }
        public string Summary_of_Investigations { get; set; }
        public Nullable<int> Release_Instruction { get; set; }
        public Nullable<int> Copy_Investigation_Report { get; set; }
        public Nullable<int> Goods_Returned_Note { get; set; }
        public Nullable<int> attached_otherDoc { get; set; }
        public string attached_other { get; set; }
        public Nullable<int> Release_Authorizedby { get; set; }
        public Nullable<System.DateTime> Release_Authorized_Date { get; set; }
        public Nullable<int> Released_By { get; set; }
        public Nullable<System.DateTime> Release_Date { get; set; }
        public Nullable<int> Received_by { get; set; }
        public Nullable<System.DateTime> Received_Date { get; set; }
        public Nullable<int> Authorized_Representative_Category { get; set; }
        public string Goods_Returned_Note_Commet { get; set; }
    }
}
