//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_xa_product
    {
        public int product_code { get; set; }
        public string product_description { get; set; }
        public string strength { get; set; }
        public string packsize { get; set; }
        public Nullable<int> carton_size_pkt { get; set; }
        public Nullable<double> carton_weight_kg { get; set; }
        public Nullable<int> product_category { get; set; }
        public Nullable<short> Basic_Unit { get; set; }
        public Nullable<bool> approved_MOH_NTG { get; set; }
        public Nullable<bool> approved_WHO { get; set; }
        public Nullable<bool> approved_FDA { get; set; }
        public Nullable<int> nda_registration { get; set; }
        public string SAP_code { get; set; }
        public Nullable<bool> ConsummableProduct { get; set; }
        public Nullable<int> ART_product_classification { get; set; }
        public string NMS_Codes { get; set; }
    }
}
