//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_crystal_aloocation_tk
    {
        public string SAP_code { get; set; }
        public string packsize { get; set; }
        public string product_description { get; set; }
        public int product_code { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public Nullable<int> Quantity_Allocated { get; set; }
        public string District_Name { get; set; }
        public string Facility { get; set; }
        public Nullable<int> AllocationYear { get; set; }
        public Nullable<int> AllocationMonth { get; set; }
    }
}
