//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_dist_schedule_maul_staff_rpt
    {
        public int FacilityCode { get; set; }
        public System.DateTime departure_date { get; set; }
        public string cp_name { get; set; }
    }
}
