//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_fo_investigation_Template
    {
        public string investigation_code { get; set; }
        public string investigation_desc { get; set; }
        public string Code { get; set; }
        public Nullable<int> e_reg_complaint_code { get; set; }
        public Nullable<int> yes_no { get; set; }
        public string Required_Evidence { get; set; }
        public string FileURL { get; set; }
        public string FileType { get; set; }
        public string Details { get; set; }
    }
}
