//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mascis
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_fo_investigation_QI_Empty
    {
        public int Id { get; set; }
        public int e_reg_complaint_code { get; set; }
        public string investigation_code { get; set; }
        public string batch_no { get; set; }
        public int product_code { get; set; }
        public Nullable<int> yes_no { get; set; }
        public string Required_Evidence { get; set; }
        public string FileURL { get; set; }
        public string FileType { get; set; }
        public string Details { get; set; }
        public string e_reg_complaint_No { get; set; }
    }
}
