// <auto-generated />
namespace mascis.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MD5Hash : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MD5Hash));
        
        string IMigrationMetadata.Id
        {
            get { return "201907121429573_MD5Hash"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
